name = "dv-chatbot"
main = "src/index.js"
compatibility_date = "2026-08-01"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "portfolio-rag"

[[kv_namespaces]]
binding = "CHAT_KV"
id = "15c0683f1e494d9d90c24ac85e8ebfab"

[vars]
ALLOWED_ORIGINS = "https://dharunvincent.com,https://www.dharunvincent.com,http://localhost:8788,http://localhost:3000"
PUBLIC_EMAIL = "dharun@dharunvincent.com"

[[rules]]
type = "Text"
globs = ["**/*.md"]
